<a href="https://colab.research.google.com/github/LeeJiwoo982/DL_study/blob/main/231012_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN 기초

In [25]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [26]:
train_X = [[1,2,3,4,5],
           [2,4,6,8,10],
           [1,3,5,7,9],
           [0,2,4,6,8]]
print(np.shape(train_X))

(4, 5)


In [27]:
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(4, 5)


## RNN은 3차원 tensor로 값을 입력받아 3차원으로 변환

In [28]:
train_X = np.array([train_X],dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


## 중요한 파라미터인 return_sequences와 return_state 두 파라미터 default값은 False

### return_sequences=True, return_state=False
* return_sequence=False 일 떄 마지막 시점 hidden state만 출력

1) 그렇다면 return_sequence가 True라면?

In [29]:
hidden_size = 3
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=False)
hidden_state=rnn(train_X)

print('train_X: {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state : {} \t shape : {}'.format(hidden_state, hidden_state.shape))

#모든 시점의 hidden_state가 출력된다.

train_X: [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state : [[[-0.99999905 -0.8557514  -0.88444495]
  [-1.         -0.99905723 -0.9535554 ]
  [-1.         -0.99684435 -0.53456885]
  [-1.         -0.9874485   0.24635144]]] 	 shape : (1, 4, 3)


### return_sequences=False, return_state=False

In [30]:
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=False)
hidden_state=rnn(train_X)

print('train_X: {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
#마지막 시점의 hidden_state 출력

train_X: [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state : [[ 0.99996305 -0.96271896 -1.        ]] 	 shape : (1, 3)


### return_sequences=True, return_state=True

In [31]:
ell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
hidden_state, last_state=rnn(train_X)


print('hidden_state : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state: {} \t shape : {}'.format(last_state, last_state.shape))

hidden_state : [[[ 0.9996864  -0.9318795  -0.9995267 ]
  [ 1.         -0.99919    -1.        ]
  [ 0.9999993  -0.99427336 -1.        ]
  [ 0.99996305 -0.96271896 -1.        ]]] 	 shape : (1, 4, 3)
last_state: [[ 0.99996305 -0.96271896 -1.        ]] 	 shape : (1, 3)


### return_sequences=False,  return_state=True

In [32]:
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=True)
hidden_state, last_state=rnn(train_X)


print('hidden_state : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state: {} \t shape : {}'.format(last_state, last_state.shape))

hidden_state : [[-0.96429646  0.71538574 -1.        ]] 	 shape : (1, 3)
last_state: [[-0.96429646  0.71538574 -1.        ]] 	 shape : (1, 3)


##토마토

"토마토"를 학습하자  
input='토토마를자먹'  
output='토마토를먹자'  

### 정의

In [33]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNNCell, Dense, TimeDistributed, RNN

idx2char = ['토', '마', '를', '먹', '자']

x_data = [[0,0,1,2,4,3]] #토 토 마 를 자 먹
y_data = [[0,1,0,2,3,4]] #토 마 토 를 먹 자/정답을 알려줌

num_classes = 5 #토큰의 갯수
input_dim = 5
sequence_len = 6 #len(x_data)/결과의 길이
learning_rate = 0.1 #학습률

데이터 변환 - 원핫인코딩

In [34]:
x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

x_one_hot

array([[[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]], dtype=float32)

In [35]:
y_one_hot

array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)

In [36]:
x_one_hot.shape
#시퀀스수, 시퀀스길이, dim 사이즈

(1, 6, 5)

### 모델링

In [37]:
model = Sequential()
cell = SimpleRNNCell(units=num_classes, input_shape=(sequence_len, input_dim))

model.add(RNN(cell=cell,
            return_sequences=True,
            return_state=False,
            input_shape=(sequence_len, input_dim)))
model.add(TimeDistributed(Dense(units=num_classes, activation='softmax')))

model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['acc'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rnn_9 (RNN)                 (None, 6, 5)              55        
                                                                 
 time_distributed_1 (TimeDi  (None, 6, 5)              30        
 stributed)                                                      
                                                                 
Total params: 85 (340.00 Byte)
Trainable params: 85 (340.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
model.fit(x_one_hot, y_one_hot, epochs=10)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 2.0107 - acc: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 21ms/step - loss: 1.6207 - acc: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 1.3516 - acc: 0.6667
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 1.1164 - acc: 0.8333
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 0.9002 - acc: 0.8333
Epoch 6/10
1/1 [==============================] - 0s 16ms/step - loss: 0.7061 - acc: 0.8333
Epoch 7/10
1/1 [==============================] - 0s 14ms/step - loss: 0.5273 - acc: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 0.3797 - acc: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 15ms/step - loss: 0.2710 - acc: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 14ms/step - loss: 0.1946 - acc: 1.0000


In [39]:
pred = model.predict(x_one_hot)
pred

1/1 [==============================] - 0s 138ms/step


array([[[9.08257663e-01, 1.87071692e-02, 5.63965878e-03, 1.21152597e-02,
         5.52802719e-02],
        [2.54459959e-02, 9.03344631e-01, 5.13453642e-03, 2.61964947e-02,
         3.98783423e-02],
        [9.51556921e-01, 1.74365030e-03, 8.10945779e-03, 7.14516907e-04,
         3.78754772e-02],
        [4.93072793e-02, 5.82268275e-03, 8.21525455e-01, 1.07555114e-01,
         1.57894474e-02],
        [2.85355784e-02, 1.63473785e-02, 1.52421400e-01, 7.70261884e-01,
         3.24337929e-02],
        [4.92685996e-02, 4.07575332e-02, 1.99630903e-03, 4.10222150e-02,
         8.66955340e-01]]], dtype=float32)

###결과

In [40]:
for i, word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis = 1)]))

토 마 토 를 먹 자


# LSTM

* 두 파라미터의 default 값은 False

## return_sequences=False, return_state=True

In [41]:
from keras.layers import LSTM

#우선 hidden_size 임의로 3
hidden_size = 3
lstm = LSTM(units=hidden_size, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state=lstm(train_X)

print('train_X        : {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state   : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state     : {} \t shape : {}'.format(last_state, last_state.shape))
print('last_cell_state: {} \t shape : {}'.format(last_cell_state, last_cell_state.shape))

train_X        : [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state   : [[ 0.03643081 -0.99195665  0.02986983]] 	 shape : (1, 3)
last_state     : [[ 0.03643081 -0.99195665  0.02986983]] 	 shape : (1, 3)
last_cell_state: [[ 0.5524434  -2.8715231   0.12162343]] 	 shape : (1, 3)


## return_sequences=True, return_state=True

In [42]:
lstm = LSTM(units=hidden_size, return_sequences=True, return_state=True)
hidden_state, last_state, last_cell_state=lstm(train_X)

print('train_X        : {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state   : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state     : {} \t shape : {}'.format(last_state, last_state.shape))
print('last_cell_state: {} \t shape : {}'.format(last_cell_state, last_cell_state.shape))

train_X        : [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state   : [[[-0.01595707 -0.05888252 -0.01447075]
  [-0.01041977 -0.00728297 -0.00043721]
  [-0.01351407 -0.02065314 -0.00047434]
  [-0.02208074 -0.05377648 -0.00099048]]] 	 shape : (1, 4, 3)
last_state     : [[-0.02208074 -0.05377648 -0.00099048]] 	 shape : (1, 3)
last_cell_state: [[-2.2662804e-02 -3.8293519e+00 -9.9190825e-04]] 	 shape : (1, 3)


##토마토

### 임포트, 정의

In [43]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNNCell, Dense, TimeDistributed, RNN

idx2char = ['토', '마', '를', '먹', '자']

x_data = [[0,0,1,2,4,3]] #토 토 마 를 자 먹
y_data = [[0,1,0,2,3,4]] #토 마 토 를 먹 자/정답을 알려줌

num_classes = 5 #토큰의 갯수
input_dim = 5
sequence_len = 6 #len(x_data)/결과의 길이
learning_rate = 0.1 #학습률

x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

###모델 쌓기

In [44]:
from keras.layers import LSTM

model = Sequential()

model.add(LSTM(units=num_classes,
               return_sequences=True,
               input_shape=(sequence_len, input_dim),activation='tanh'))
model.add(Dense(32, activation='relu'))
model.add(Dense(units=num_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['acc'])

model.fit(x_one_hot, y_one_hot, epochs=10)
pred = model.predict(x_one_hot)

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 1.6091 - acc: 0.1667
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 1.5193 - acc: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 1.3719 - acc: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 1.1383 - acc: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 0.8674 - acc: 0.8333
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 0.5836 - acc: 0.8333
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 0.4153 - acc: 0.8333
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 0.2949 - acc: 0.8333
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.2585 - acc: 0.8333
Epoch 10/10
1/1 [==============================] - 0s 394ms/step


In [45]:
pred

array([[[4.1194665e-01, 5.8735180e-01, 3.8523951e-05, 1.1553899e-07,
         6.6291390e-04],
        [1.6304682e-01, 8.3692491e-01, 4.6067686e-07, 2.3742178e-10,
         2.7693532e-05],
        [9.0912706e-01, 9.0140030e-02, 7.2334288e-04, 9.5237567e-08,
         9.5480209e-06],
        [1.3265967e-03, 3.0842384e-05, 9.9269003e-01, 5.8867373e-03,
         6.5778571e-05],
        [1.6193627e-07, 1.4553394e-09, 8.9546840e-04, 9.9875295e-01,
         3.5148693e-04],
        [1.8588652e-06, 1.6343303e-05, 3.6320278e-09, 3.8578341e-06,
         9.9997795e-01]]], dtype=float32)

### 결과

In [46]:
for i, word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis = 1)]))

마 마 토 를 먹 자


# GRU
Grated Recurrent Unit

## return_sequences = False, return_state=True

In [50]:
from keras.layers import GRU

hidden_size = 3
gru= GRU(units=hidden_size, return_sequences=False, return_state=True)
hidden_state, last_state = gru(train_X)

print('train_X        : {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state   : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state     : {} \t shape : {}'.format(last_state, last_state.shape))

train_X        : [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state   : [[-0.9984235  -0.8571842  -0.34000686]] 	 shape : (1, 3)
last_state     : [[-0.9984235  -0.8571842  -0.34000686]] 	 shape : (1, 3)


## return_sequences=True, return_state=True

In [52]:
gru= GRU(units=hidden_size, return_sequences=True, return_state=True)
hidden_state, last_state = gru(train_X)

print('train_X        : {} \t shape : {}'.format(train_X, train_X.shape))
print('hidden_state   : {} \t shape : {}'.format(hidden_state, hidden_state.shape))
print('last_state     : {} \t shape : {}'.format(last_state, last_state.shape))

train_X        : [[[ 1.  2.  3.  4.  5.]
  [ 2.  4.  6.  8. 10.]
  [ 1.  3.  5.  7.  9.]
  [ 0.  2.  4.  6.  8.]]] 	 shape : (1, 4, 5)
hidden_state   : [[[ 0.01492814  0.56057435  0.01067822]
  [ 0.02457547  0.8229378   0.01089729]
  [-0.03197804  0.929557    0.01126008]
  [-0.265835    0.9727646   0.01160135]]] 	 shape : (1, 4, 3)
last_state     : [[-0.265835    0.9727646   0.01160135]] 	 shape : (1, 3)


##토마토

###정의

In [54]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNNCell, Dense, TimeDistributed, RNN
from keras.layers import GRU

idx2char = ['토', '마', '를', '먹', '자']

x_data = [[0,0,1,2,4,3]] #토 토 마 를 자 먹
y_data = [[0,1,0,2,3,4]] #토 마 토 를 먹 자/정답을 알려줌

num_classes = 5 #토큰의 갯수
input_dim = 5
sequence_len = 6 #len(x_data)/결과의 길이
learning_rate = 0.1 #학습률

###모델링

In [55]:
model = Sequential()

model.add(GRU(units=num_classes,
               return_sequences=True,
               input_shape=(sequence_len, input_dim),activation='tanh'))
model.add(Dense(32, activation='relu'))
model.add(Dense(units=num_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['acc'])

model.fit(x_one_hot, y_one_hot, epochs=10)
pred = model.predict(x_one_hot)

Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 1.6167 - acc: 0.1667
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 1.4022 - acc: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 1.1844 - acc: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 0.8303 - acc: 0.6667
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 0.4900 - acc: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 0.3530 - acc: 0.8333
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.2294 - acc: 0.8333
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 0.2313 - acc: 0.8333
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.1635 - acc: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.1737 - acc: 0.8333


1/1 [==============================] - 0s 396ms/step


###결과

In [56]:
for i, word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis = 1)]))

토 마 토 를 먹 자
